import React from 'react';
import { PageContainer } from '../../../components/layout/PageContainer';
import { KpiCard } from '../../../components/common/KpiCard';
import { Table, Column } from '../../../components/common/Table';
import { StatusBadge } from '../../../components/common/StatusBadge';

interface AppointmentRow {
  time: string;
  patient: string;
  doctor: string;
  status: string;
}

interface ActivityItem {
  id: string;
  title: string;
  time: string;
  type: 'report' | 'prescription' | 'payment' | 'appointment';
}

export const Dashboard: React.FC = () => {
  const appointments: AppointmentRow[] = [
    { time: '10:00 AM', patient: 'Rahul Kumar', doctor: 'Dr. Ravi (Cardiology)', status: 'Waiting' },
    { time: '10:30 AM', patient: 'Priya Sharma', doctor: 'Dr. Kumar (General)', status: 'In Consultation' },
    { time: '11:00 AM', patient: 'Arun Rao', doctor: 'Dr. Smith (Orthopedics)', status: 'Completed' },
    { time: '11:30 AM', patient: 'Deepa Verma', doctor: 'Dr. Ravi (Cardiology)', status: 'Waiting' },
    { time: '12:00 PM', patient: 'Karan Patel', doctor: 'Dr. Mehta (Neurology)', status: 'Pending' },
  ];

  const activities: ActivityItem[] = [
    { id: '1', title: 'Lab report uploaded for Priya Sharma', time: '10 mins ago', type: 'report' },
    { id: '2', title: 'Prescription generated by Dr. Ravi', time: '25 mins ago', type: 'prescription' },
    { id: '3', title: 'Payment of ₹1,500 received from Arun Rao', time: '40 mins ago', type: 'payment' },
    { id: '4', title: 'New appointment scheduled for Deepa Verma', time: '1 hour ago', type: 'appointment' },
    { id: '5', title: 'Pharmacy order #ORD-402 fulfilled', time: '2 hours ago', type: 'prescription' },
  ];

  const appointmentColumns: Column<AppointmentRow>[] = [
    { header: 'Time', accessor: 'time', className: 'font-semibold text-slate-900' },
    { header: 'Patient Name', accessor: 'patient' },
    { header: 'Doctor / Dept', accessor: 'doctor', className: 'text-slate-600' },
    {
      header: 'Status',
      accessor: row => <StatusBadge status={row.status} />,
    },
  ];

  return (
    <PageContainer
      title="Good Morning, Admin"
      description="Here is today's hospital operations overview and clinical metrics."
      actions={
        <div className="flex items-center gap-2">
          <button className="px-3.5 py-2 bg-white border border-slate-200 text-slate-700 rounded-lg text-xs font-semibold hover:bg-slate-50 transition-colors shadow-sm">
            Export Report
          </button>
          <button className="px-3.5 py-2 bg-sky-600 text-white rounded-lg text-xs font-semibold hover:bg-sky-700 transition-colors shadow-sm">
            + New Appointment
          </button>
        </div>
      }
    >
      {/* 1. KPI Summary Cards (4 Cards Only) */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
        <KpiCard title="Patients" value="128" subtext="+12 registered today" icon="👥" trend="up" />
        <KpiCard title="Appointments" value="42" subtext="8 pending review" icon="📅" trend="neutral" />
        <KpiCard title="Lab Tests" value="18" subtext="5 pending reports" icon="🧪" trend="down" />
        <KpiCard title="Revenue" value="₹84,500" subtext="+8.4% from yesterday" icon="💳" trend="up" />
      </div>

      {/* 2. Main Content Grid (2 Columns) */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Today's Appointments Table (2/3 width) */}
        <div className="lg:col-span-2 space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-bold text-slate-900">Today's Appointments</h3>
            <span className="text-xs font-semibold text-sky-600 hover:underline cursor-pointer">View All</span>
          </div>
          <Table
            columns={appointmentColumns}
            data={appointments}
            keyExtractor={row => row.time + row.patient}
          />
        </div>

        {/* Recent Activity List (1/3 width) */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold text-slate-900">Recent Activity</h3>
          <div className="hms-card p-4 space-y-4">
            {activities.map(act => (
              <div key={act.id} className="flex items-start gap-3 pb-3 border-b border-slate-100 last:pb-0 last:border-none">
                <span className="w-2 h-2 rounded-full bg-sky-500 mt-1.5 shrink-0"></span>
                <div>
                  <p className="text-xs font-medium text-slate-900 leading-snug">{act.title}</p>
                  <span className="text-[10px] text-slate-400 font-medium">{act.time}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </PageContainer>
  );
};

export default Dashboard;
